### ISSUE TITLE
lineage os updater. be directory that user want

### ISSUE THREAD

**Issue by peturbg** [julianxhokaxhiu/LineageOTA#39]
Hi guys

In the readme it comment it is lineage direcotry, so is there way to change it to be directory that user want. For example: https://yourwebsite.ru/samsung/api

happy 24 and 25

**Comment by peturbg** [comment]
so how to make this updater to point to this. when user trigger lineage update
GET /samsung/api/v1/93/unofficial/1a4476ada HTTP/1.1" 404 4038 "-" "Dalvik/2.1.0 (Linux; U; Android 7.1.2; samsung 93 Build/NJH47F)"

**Comment by julianxhokaxhiu** [comment]
Sorry, this is not a support board. For that, feel free to use the dedicated XDA thread. Best regards.

**Comment by Charles-IV** [comment]
I think this is a good idea, and you could have asked on xda before insulting the whole forum.
Julian - perhaps you could add a contributing file to explain that most discussion should be on the thread, but code related issues/whatever it is should be here, or just simply add it to the readme, as a few issues have been closed because they would be better on the xda thread.
Sorry for a kind of off-topic comment.

**Comment by julianxhokaxhiu** [comment]
Thank you for the suggestion @Charles-IV :)

Feel free to review and enhance with a dedicated PR.
