### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by AlexDeltax** [julianxhokaxhiu/LineageOTA#48]
Hi there. Your project is enormous. Are you planning any kind of statistics?
For example how much pings and how much downloads?
I know, that this kind of statistics is a bit inaccurate, but it will be pretty good to have one.

**Comment by julianxhokaxhiu** [comment]
Hi, thanks. When I first created this, the mission was about providing support to one of the Custom ROMs I was using on my Samsung Galaxy S2, at that period of time.

Since then I decided to make this open source and publish it on XDA. Luckily the community liked it and decided to support this, not just use it :)

Related to your question, I would be glad if someone takes the time ( or you yourself ) to implement this. I'm totally open to review a PR. Although for now I do not have nor the time, nor the interest to implement this.

Thank you for the idea though. It's pretty good.

**Comment by julianxhokaxhiu** [comment]
Going back to this one, if you want to have easily these kind of statistics you can put LineageOTA behind a reverse proxy and collect this info through logs ( or other means ) that will be generated by the Reverse Proxy.

Since this project is meant anyway to be used with a RP on top, I'll close this issue as I don't see any value in adding this built-in on LineageOTA.
