### ISSUE TITLE
calculating md5sum expensive and unnecessary?

### ISSUE THREAD

**Issue by bananer** [julianxhokaxhiu/LineageOTA#96]
Responses often are very slow or even time out for me. I dug into it and `md5sum` is running for multiple minutes for every zip file. It's called from [here](https://github.com/julianxhokaxhiu/LineageOTA/blob/b2fa3b7d6f8c05ba2ba74f240909378605172ac2/src/Helpers/BuildLocal.php#L125).

Comparing with the output of LineageOS' official OTA server, it does not even include a zip's md5sum: e.g. https://download.lineageos.org/api/v1/taimen/nightly/full

Could it be that md5 calculation is actually unnecessary? If it servers some case, could we make it optional?

**Comment by julianxhokaxhiu** [comment]
I think it was used back in the CyanogenMod era, probably deprecated on LineageOS. It really depends on how the updater app logic is implemented.

The idea here is that if you want to speed it up, you provide already the `.md5sum` file next to your ZIP file, otherwise it will be done by the server. This file is usually generated by the build scripts, so it costs nothing to copy it next to the ZIP file.
